services:
  spring:
    container_name: spring-backend
    depends_on:
      - mysql
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysql
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url=jdbc:mysql": "//jdbc:mysql:3306/spring-test",
        "spring.datasource.username": "root",
        "spring.datasource.password": "password",
        "spring.jpa.hibernate.ddl-auto": "update"
        }'

  mysql:
    container_name: mysql-db
    image: mysql:5.7
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password

# run: docker compose up -d
